SELECT DISTINCT CITY FROM STATION WHERE CITY NOT LIKE "%A" AND CITY NOT LIKE "%E" AND CITY NOT LIKE "%I" AND CITY NOT LIKE "%O" AND CITY NOT LIKE "%U";

#this works faster and easier
SELECT DISTINCT CITY FROM STATION WHERE NOT RIGHT(CITY,1)IN("A","E","I","O","U");
SELECT DISTINCT CITY FROM STATION WHERE CITY NOT REGEXP '[AEIOU]$';
